name: FruityEssentials
version: ${project.version}
main: net.fruchtlabor.fruityessentials.FruityEssentials
api-version: 1.13
authors: [Nino, Patrick]
description: CMI System für Fruchtlabor.net
website: Fruchtlabor.net
commands:
  money:
    aliases: ['geld']
    description: Der Geldbefehl
  bank:
    description: Der Bankbefehl
  tp:
    description: Teleport
